#created on: 05-Oct-2008
package TestingContract

# Import Java classes for EROP support
import uk.ac.ncl.erop.*;

# Global variables (that is, persistent objects passed from outside)
global RelevanceEngine engine;
global EventLogger logger;
global ROPSet ropBuyer;
global ROPSet ropSeller;
global BusinessOperation purchaseOrder;
global BusinessOperation finePayment;

rule "Initialization"
	when
		$e: Event (type == "init")
	then 
		# Nothing happens
		System.out.println("Initialization rule triggered");
end

rule "Event capture"
	when
		$e: Event (type != "init")
	then 
		System.out.println("Event received, second rule triggered");
		System.out.println("Event of type "+$e.getType()+" from "+$e.getOriginator()+" to "+$e.getResponder());
end
